### ISSUE TITLE
ajouter l'info sur les unités

### ISSUE THREAD

**Issue by vgenot** [SciQLop/speasy_proxy#4]
ajouter les unités sur l'axe Y ou sur dans la boite avec les parametres

**Comment by jeandet** [comment]
Fait, [exemple1](http://sciqlop.lpp.polytechnique.fr/cache-dev/get_data?format=html_bokeh&path=csa/C1_CP_FGM_SPIN/B_vec_xyz_gse__C1_CP_FGM_SPIN&start_time=2008-02-14T07:56:24.500000000&stop_time=2008-02-14T18:01:34.300000000), [exemple2](http://sciqlop.lpp.polytechnique.fr/cache-dev/get_data?format=html_bokeh&path=cda/MMS1_FPI_FAST_L2_DIS-MOMS/mms1_dis_energyspectr_mx_fast&start_time=2021-10-31T04:21:54.434Z&stop_time=2021-11-01T05:39:54.434Z).

**Comment by vgenot** [comment]
ok
