### ISSUE TITLE
boites qui se superposent / 1 seule boite

### ISSUE THREAD

**Issue by vgenot** [SciQLop/speasy_proxy#5]
une seule boite avec un seul temps plutot que de le repeter 3 fois avec 3 boites qui se chevauchent vu qu'on sait que c'est un vector 'property = vector'

![image](https://user-images.githubusercontent.com/49245262/198564804-a764d2d0-374e-4ca1-ace9-8ac496de7312.png)

**Comment by jeandet** [comment]
Avec Bokeh, c'est assez galère à faire. Pour le moment, j'ai un peu triché et attachnat le tooltip au dernier graph et en affichant les valeurs de toutes le composantes dans ce tooltip.

http://sciqlop.lpp.polytechnique.fr/cache-dev/get_data?format=html_bokeh&path=csa/C1_CP_FGM_SPIN/B_vec_xyz_gse__C1_CP_FGM_SPIN&start_time=2008-02-14T07:56:24.500000000&stop_time=2008-02-14T18:01:34.300000000

**Comment by vgenot** [comment]
ok
