### ISSUE TITLE
axe des temps

### ISSUE THREAD

**Issue by vgenot** [SciQLop/speasy_proxy#6]
enlever "time" sur l'axe
ajouter la date ou les dates selon la longueur de l'intervalle

**Comment by jeandet** [comment]
Je propose ça:
http://sciqlop.lpp.polytechnique.fr/cache-dev/get_data?format=html_bokeh&path=csa/C1_CP_FGM_SPIN/B_vec_xyz_gse__C1_CP_FGM_SPIN&start_time=2008-02-14T07:56:24.500000000&stop_time=2008-02-14T18:01:34.300000000

**Comment by vgenot** [comment]
ok
